spring:
  profiles:
    active: ${PROFILE:prod}

influxdb:
  url: http://localhost:8086
  token: aoob8dMzYujpLX5xOYCm84cpgvj0_gsAdzfYG8xTGC32kdRb84QFCE6Bf61fJKZwnvZQGXZxoV1nRGZZcTyI-g==
  org: getchan
  bucket: NamuWikiChange

collect:
  delay: 10 # seconds