spring:
  profiles:
    active: ${PROFILE:dev}

collect:
  delay: 10 # seconds

last-collected-set:
  limit: 15

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: health,info