spring:
  profiles:
    active: ${PROFILE:dev}
  cloud:
    function:
      bindings:
        sendEvents-out-0: output
    stream:
      bindings:
        output:
          destination: namu-wiki-change

collect:
  delay: 10 # seconds

last-collected-set:
  limit: 15
  json-file: src/main/resources/lastCollect.json

logging:
  level:
    root: info
